version: "3"
services:
  spigot:
    image: "${DOCKER_HUB_USERNAME}/${IMG_PREFIX}spigot:${REV}"
    ports:
      - "25565:25565"
    volumes:
      - ${PWD}:/serverdir
    environment:
      - EULA=true
      - XMS=${XMS}
      - XMX=${XMX}
