version: "3"
services:
  spigot:
    image: "saphirevert/saph-spigot:1.15.2"
    ports:
      - "25565:25565"
    volumes:
      - ${PWD}:/serverdir
    environment:
      - EULA=true
      - XMS="256M"
      - XMX="1G"
