version: "3"
services:
  spigot:
    image: "${DOCKER_HUB_USERNAME}/${IMG_PREFIX}spigot:${REV}"
    ports:
      - "25565:25565"
    # This has to be smarter, e.g. mount each file and sub-directories
    volumes:
      - ${PWD}/data:${SPIGOTDIR}

    environment:
      - EULA=true
      - XMS=${XMS}
      - XMX=${XMX}
      - FORCE_DOWNLOAD=false

      - BROADCAST-RCON-TO-OPS=${BROADCAST-RCON-TO-OPS}
      - VIEW-DISTANCE=${VIEW-DISTANCE}
      - MAX-BUILD-HEIGHT=${MAX-BUILD-HEIGHT}
      - SERVER-IP=${SERVER-IP}
      - LEVEL-SEED=${LEVEL-SEED}
      - RCON-PORT=${RCON-PORT}
      - GAMEMODE=${GAMEMODE}
      - SERVER-PORT=${SERVER-PORT}
      - ALLOW-NETHER=${ALLOW-NETHER}
      - ENABLE-COMMAND-BLOCK=${ENABLE-COMMAND-BLOCK}
      - ENABLE-RCON=${ENABLE-RCON}
      - ENABLE-QUERY=${ENABLE-QUERY}
      - OP-PERMISSION-LEVEL=${OP-PERMISSION-LEVEL}
      - PREVENT-PROXY-CONNECTIONS=${PREVENT-PROXY-CONNECTIONS}
      - GENERATOR-SETTINGS=${GENERATOR-SETTINGS}
      - RESOURCE-PACK=${RESOURCE-PACK}
      - LEVEL-NAME=${LEVEL-NAME}
      - RCON-PASSWORD=${RCON-PASSWORD}
      - PLAYER-IDLE-TIMEOUT=${PLAYER-IDLE-TIMEOUT}
      - MOTD=${MOTD}
      - QUERY-PORT=${QUERY-PORT}
      - DEBUG=${DEBUG}
      - FORCE-GAMEMODE=${FORCE-GAMEMODE}
      - HARDCORE=${HARDCORE}
      - WHITE-LIST=${WHITE-LIST}
      - BROADCAST-CONSOLE-TO-OPS=${BROADCAST-CONSOLE-TO-OPS}
      - PVP=${PVP}
      - SPAWN-NPCS=${SPAWN-NPCS}
      - GENERATE-STRUCTURES=${GENERATE-STRUCTURES}
      - SPAWN-ANIMALS=${SPAWN-ANIMALS}
      - SNOOPER-ENABLED=${SNOOPER-ENABLED}
      - DIFFICULTY=${DIFFICULTY}
      - FUNCTION-PERMISSION-LEVEL=${FUNCTION-PERMISSION-LEVEL}
      - NETWORK-COMPRESSION-THRESHOLD=${NETWORK-COMPRESSION-THRESHOLD}
      - LEVEL-TYPE=${LEVEL-TYPE}
      - SPAWN-MONSTERS=${SPAWN-MONSTERS}
      - MAX-TICK-TIME=${MAX-TICK-TIME}
      - ENFORCE-WHITELIST=${ENFORCE-WHITELIST}
      - USE-NATIVE-TRANSPORT=${USE-NATIVE-TRANSPORT}
      - MAX-PLAYERS=${MAX-PLAYERS}
      - RESOURCE-PACK-SHA1=${RESOURCE-PACK-SHA1}
      - SPAWN-PROTECTION=${SPAWN-PROTECTION}
      - ONLINE-MODE=${ONLINE-MODE}
      - ALLOW-FLIGHT=${ALLOW-FLIGHT}
      - MAX-WORLD-SIZE=${MAX-WORLD-SIZE}
